apiVersion: v2
appVersion: "0.0.1"

name: vechr-observability
description: Vechr for observability


keywords:
- Vechr
- IoT

type: application
version: 0.0.1
home: https://github.com/vechr
maintainers:
  - name: zulfikar
    url: https://github.com/zulfikar4568
    email: isnaen70@gmail.com

icon: https://raw.githubusercontent.com/vechr/vechr-atlas/master/images/logo.svg

dependencies:
  - name: elasticsearch
    version: 8.5.1
    repository: https://helm.elastic.co
    condition: elasticsearch.enabled

  - name: logstash
    version: 8.5.1
    repository: https://helm.elastic.co
    condition: logstash.enabled

  - name: kibana
    version: 8.5.1
    repository: https://helm.elastic.co
    condition: kibana.enabled